### ISSUE TITLE
Discontinue the use of Cloudflare on Oasis

### ISSUE THREAD

**Issue by leafcutterant** [makerdao/oasis-direct-proxy#2]
The ReCaptcha challenge on the Cloudflare screen won't display for those who try to access the site from Tor, preventing them from using Oasis. Moreover, Cloudflare represents a centralized surveillance checkpoint, and it uses Google ReCaptcha - a tool that utilizes user input to train Google's AI, which then it [lends](https://gizmodo.com/google-is-helping-the-pentagon-build-ai-for-drones-1823464533) to the US [military](https://joeyh.name/blog/entry/prove_you_are_not_an_Evil_corporate_person/) for [drone strike targeting](https://theintercept.com/2018/03/06/google-is-quietly-providing-ai-technology-for-drone-strike-targeting-project/).

This is completely unethical from every point of view. We are in crypto, there are other ways to protect a website from DDoS. Please boycott these tools and use something else.

**Comment by leafcutterant** [comment]
@gbalabasquer, do you care to even answer?

**Comment by gbalabasquer** [comment]
@leafcutterant I do not have anything to reply to it, and honestly I thought you had just confused the place where to put your complaint. This specific project is a solidity source that nothing has to do with Cloudflare.
Besides that, our UIs are open source, so you are free to run them locally and avoid feeding the US military.
Anyway you are free to join chat.makerdao.com to raise your voice.
